baseurl = "https://chatanu.ga/"
languageCode = "en-us"
title = "Chatanu. ga"
theme = "hyde"

[Author]
    name = "Eran Zimbler"

[Permalinks]
    blog = "/:year/:month/:filename/"
    code = "/:filename/"

[params]
    twitter = "https://twitter.com/zimbler"
    linkedin = "https://il.linkedin.com/in/zimbler"
    github = "https://github.com/srgrn"
    disqusShortname = "chatanuga"
	description = "Interesting tidbits"